name: Deploy
on:
  push:

env:
  DOTNET_NOLOGO: true
jobs:
  staging:
    runs-on: windows-2019 # Code signing requirement https://github.com/NuGet/Home/issues/7939
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install Eset
        run: |
            Import-Module BitsTransfer
            Start-BitsTransfer -Source https://download.eset.com/com/eset/apps/business/eea/windows/latest/eea_nt64.msi
            msiexec /i eea_nt64.msi /qn /norestart APPDIR=C:\ESET\ PRODUCT_LANG=1033 PRODUCT_LANG_CODE=en-us
            echo "C:\ESET\" >> $GITHUB_PATH
        shell: pwsh
      - name: Scan
        run: . ecls /subdir /files /arch /clean-mode=none
