name: Deploy
on:
  push:

env:
  DOTNET_NOLOGO: true
jobs:
  staging:
    runs-on: windows-2019 # Code signing requirement https://github.com/NuGet/Home/issues/7939
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install Eset
        run: |
          choco install eset-antivirus
        shell: pwsh
      - name: Scan
        run: |
          & "C:\Program Files\ESET\ESET Security\ecls.exe" /subdir /files /arch /clean-mode=none
        shell: pwsh
